export { default as GenresList } from './GenresList/GenresList'
export { default as MainMusics } from './MainMusics/MainMusics'
export { default as QueryMusics } from './QueryMusics/QueryMusics'
export { default as ArtistsByGenre } from './ArtistsByGenre/ArtistsByGenre'
export { default as MusicsByGenre } from './MusicsByGenre/MusicsByGenre'
export { default as Header } from './header/Header'